name: "Composite togetyher"
description: "Testing composite run - pass into nested"

inputs:
  who-to-greet:
    description: “test hello world thingy”
    required: true

runs:
  using: "composite"
  steps:
  # checkout this repo
  - name: Checkout Repo
    uses: actions/checkout@v2.3.4

  # checkout the private repo containing the action to run
  - name: Checkout GitHub Action Repo
    uses: actions/checkout@v2.3.4
    with:
      repository: zippedydoodah/action-nested
      path: ci/action-nested

  - name: build and push docker image to local repo
    id: docker_build
    uses: docker/build-push-action@v2
    with:
      context: .
      push: true
      tags: action-first-level/test-image:latest


  - name: Run nested docker action
    id: action-nested
    uses: ./ci/action-nested
    with:
      who-to-greet: "${{ inputs.who-to-greet }}"
