name: "Composite togetyher"
description: "Testing composite run - pass into nested"

inputs:
  who-to-greet-docker:
    description: “test hello world thingy”
    required: true
  who-to-greet-js:
    description: “Joe aswell!”
    required: true

runs:
  using: "composite"
  steps:
  # checkout this repo
  - name: Checkout Repo
    uses: actions/checkout@v2.3.4

  # checkout the private repo containing the action to run
  - name: Checkout simple js
    uses: actions/checkout@v2.3.4
    with:
      repository: zippedydoodah/action-simple-js
      path: ci/action-simple-js

  - name: Simple JS action step
    id: hello
    uses: ./ci/action-simple-js
    with:
      who-to-greet: "${{ inputs.who-to-greet-js }}"
  # Use the output from the nested `hello` step
  - name: Get the output time WITHIN COMPOSITE
    run: echo "The time was ${{ steps.hello.outputs.time }}"

  # checkout the private repo containing the action to run
  - name: Checkout action-nested
    uses: actions/checkout@v2.3.4
    with:
      repository: zippedydoodah/action-nested
      path: ci/action-nested

  - name: Run nested docker action
    id: action-nested
    uses: ./ci/action-nested
    with:
      who-to-greet: "${{ inputs.who-to-greet-docker }}"
