name: First Level

on: push

runs:
  using: "composite"
  steps:
  # checkout this repo
  - name: Checkout Repo
    uses: actions/checkout@v2.3.4

  # checkout the private repo containing the action to run
  - name: Checkout GitHub Action Repo
    uses: actions/checkout@v2.3.4
    with:
      repository: zippedydoodah/action-nested
      path: ci/action-nested

  - name: Nested action
    id: action-nested
    uses: ./ci/action-nested
    with:
      who-to-greet: "mr Joe"
